# TCL File Generated by Component Editor 15.1
# Thu Feb 16 14:08:15 EST 2017
# DO NOT MODIFY


# 
# ycbcr_to_rgb_accelerator "ycbcr_to_rgb_accelerator" v1.0
#  2017.02.16.14:08:15
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module ycbcr_to_rgb_accelerator
# 
set_module_property DESCRIPTION ""
set_module_property NAME ycbcr_to_rgb_accelerator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ycbcr_to_rgb_accelerator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ycbcr_to_rgb_streaming_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ycbcr_to_rgb_streaming_interface.vhd VHDL PATH ycbcr_to_rgb/ycbcr_to_rgb_streaming_interface.vhd
add_fileset_file ycbcr_to_rgb.vhd VHDL PATH ycbcr_to_rgb/ycbcr_to_rgb.vhd
add_fileset_file ram_infer.vhd VHDL PATH ycbcr_to_rgb/ram_infer.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset_n
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source i_rgb_ready ready Input 1
add_interface_port avalon_streaming_source o_rgb_data data Output 32
add_interface_port avalon_streaming_source o_rgb_valid valid Output 1


# 
# connection point avalon_streaming_sink_cr
# 
add_interface avalon_streaming_sink_cr avalon_streaming end
set_interface_property avalon_streaming_sink_cr associatedClock clock
set_interface_property avalon_streaming_sink_cr associatedReset reset_n
set_interface_property avalon_streaming_sink_cr dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_cr errorDescriptor ""
set_interface_property avalon_streaming_sink_cr firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_cr maxChannel 0
set_interface_property avalon_streaming_sink_cr readyLatency 0
set_interface_property avalon_streaming_sink_cr ENABLED true
set_interface_property avalon_streaming_sink_cr EXPORT_OF ""
set_interface_property avalon_streaming_sink_cr PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_cr CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_cr SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_cr o_cr_ready ready Output 1
add_interface_port avalon_streaming_sink_cr i_cr_data data Input 32
add_interface_port avalon_streaming_sink_cr i_cr_valid valid Input 1


# 
# connection point avalon_streaming_sink_y
# 
add_interface avalon_streaming_sink_y avalon_streaming end
set_interface_property avalon_streaming_sink_y associatedClock clock
set_interface_property avalon_streaming_sink_y associatedReset reset_n
set_interface_property avalon_streaming_sink_y dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_y errorDescriptor ""
set_interface_property avalon_streaming_sink_y firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_y maxChannel 0
set_interface_property avalon_streaming_sink_y readyLatency 0
set_interface_property avalon_streaming_sink_y ENABLED true
set_interface_property avalon_streaming_sink_y EXPORT_OF ""
set_interface_property avalon_streaming_sink_y PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_y CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_y SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_y o_y_ready ready Output 1
add_interface_port avalon_streaming_sink_y i_y_valid valid Input 1
add_interface_port avalon_streaming_sink_y i_y_data data Input 32


# 
# connection point avalon_streaming_sink_cb
# 
add_interface avalon_streaming_sink_cb avalon_streaming end
set_interface_property avalon_streaming_sink_cb associatedClock clock
set_interface_property avalon_streaming_sink_cb associatedReset reset_n
set_interface_property avalon_streaming_sink_cb dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_cb errorDescriptor ""
set_interface_property avalon_streaming_sink_cb firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_cb maxChannel 0
set_interface_property avalon_streaming_sink_cb readyLatency 0
set_interface_property avalon_streaming_sink_cb ENABLED true
set_interface_property avalon_streaming_sink_cb EXPORT_OF ""
set_interface_property avalon_streaming_sink_cb PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink_cb CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink_cb SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink_cb i_cb_data data Input 32
add_interface_port avalon_streaming_sink_cb i_cb_valid valid Input 1
add_interface_port avalon_streaming_sink_cb o_cb_ready ready Output 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset_n Input 1

